# nasdaq_companies.py

# A dictionary mapping company names and tickers (case-insensitive) to their official ticker symbols
company_to_ticker = {
    "apple": "AAPL",
    "aapl": "AAPL",
    "airbnb": "ABNB",
    "abnb": "ABNB",
    "adobe": "ADBE",
    "adbe": "ADBE",
    "analog devices": "ADI",
    "adi": "ADI",
    "automatic data processing": "ADP",
    "adp": "ADP",
    "autodesk": "ADSK",
    "adsk": "ADSK",
    "american electric power": "AEP",
    "aep": "AEP",
    "applied materials": "AMAT",
    "amat": "AMAT",
    "advanced micro devices": "AMD",
    "amd": "AMD",
    "amgen": "AMGN",
    "amgn": "AMGN",
    "amazon": "AMZN",
    "amzn": "AMZN",
    "ansys": "ANSS",
    "anss": "ANSS",
    "applovin": "APP",
    "app": "APP",
    "arm holdings": "ARM",
    "arm": "ARM",
    "asml holding": "ASML",
    "asml": "ASML",
    "broadcom": "AVGO",
    "avgo": "AVGO",
    "axon enterprise": "AXON",
    "axon": "AXON",
    "astrazeneca": "AZN",
    "azn": "AZN",
    "biogen": "BIIB",
    "biib": "BIIB",
    "booking holdings": "BKNG",
    "bkng": "BKNG",
    "baker hughes": "BKR",
    "bkr": "BKR",
    "coca-cola europacific partners": "CCEP",
    "ccep": "CCEP",
    "cadence design systems": "CDNS",
    "cdns": "CDNS",
    "cdw corporation": "CDW",
    "cdw": "CDW",
    "constellation energy": "CEG",
    "ceg": "CEG",
    "charter communications": "CHTR",
    "chtr": "CHTR",
    "comcast": "CMCSA",
    "cmcsa": "CMCSA",
    "costco": "COST",
    "cost": "COST",
    "copart": "CPRT",
    "cprt": "CPRT",
    "crowdstrike": "CRWD",
    "crwd": "CRWD",
    "cisco": "CSCO",
    "csco": "CSCO",
    "costar group": "CSGP",
    "csgp": "CSGP",
    "csx corporation": "CSX",
    "csx": "CSX",
    "cintas": "CTAS",
    "ctas": "CTAS",
    "cognizant": "CTSH",
    "ctsh": "CTSH",
    "doordash": "DASH",
    "dash": "DASH",
    "datadog": "DDOG",
    "ddog": "DDOG",
    "dexcom": "DXCM",
    "dxcm": "DXCM",
    "electronic arts": "EA",
    "ea": "EA",
    "exelon": "EXC",
    "exc": "EXC",
    "diamondback energy": "FANG",
    "fang": "FANG",
    "fastenal": "FAST",
    "fast": "FAST",
    "fortinet": "FTNT",
    "ftnt": "FTNT",
    "ge healthcare": "GEHC",
    "gehc": "GEHC",
    "globalfoundries": "GFS",
    "gfs": "GFS",
    "gilead sciences": "GILD",
    "gild": "GILD",
    "alphabet (class c)": "GOOG",
    "goog": "GOOG",
    "alphabet (class a)": "GOOGL",
    "googl": "GOOGL",
    "honeywell": "HON",
    "hon": "HON",
    "idexx laboratories": "IDXX",
    "idxx": "IDXX",
    "intel": "INTC",
    "intc": "INTC",
    "intuit": "INTU",
    "intu": "INTU",
    "intuitive surgical": "ISRG",
    "isrg": "ISRG",
    "keurig dr pepper": "KDP",
    "kdp": "KDP",
    "kraft heinz": "KHC",
    "khc": "KHC",
    "kla corporation": "KLAC",
    "klac": "KLAC",
    "linde": "LIN",
    "lin": "LIN",
    "lam research": "LRCX",
    "lrcx": "LRCX",
    "lululemon": "LULU",
    "lulu": "LULU",
    "marriott international": "MAR",
    "mar": "MAR",
    "microchip technology": "MCHP",
    "mchp": "MCHP",
    "mongodb": "MDB",
    "mdb": "MDB",
    "mondelez": "MDLZ",
    "mdlz": "MDLZ",
    "mercadolibre": "MELI",
    "meli": "MELI",
    "meta platforms": "META",
    "meta": "META",
    "monster beverage": "MNST",
    "mnst": "MNST",
    "marvell technology": "MRVL",
    "mrvl": "MRVL",
    "microsoft": "MSFT",
    "msft": "MSFT",
    "microstrategy": "MSTR",
    "mstr": "MSTR",
    "micron technology": "MU",
    "mu": "MU",
    "netflix": "NFLX",
    "nflx": "NFLX",
    "nvidia": "NVDA",
    "nvda": "NVDA",
    "nxp semiconductors": "NXPI",
    "nxpi": "NXPI",
    "old dominion freight": "ODFL",
    "odfl": "ODFL",
    "on semiconductor": "ON",
    "on": "ON",
    "o'reilly automotive": "ORLY",
    "orly": "ORLY",
    "palo alto networks": "PANW",
    "panw": "PANW",
    "paychex": "PAYX",
    "paccar": "PCAR",
    "pdd holdings": "PDD",
    "pepsico": "PEP",
    "palantir technologies": "PLTR",
    "paypal": "PYPL",
    "qualcomm": "QCOM",
    "regeneron pharmaceuticals": "REGN",
    "roper technologies": "ROP",
    "ross stores": "ROST",
    "starbucks": "SBUX",
    "synopsys": "SNPS",
    "atlassian": "TEAM",
    "t-mobile": "TMUS",
    "tesla": "TSLA",
    "the trade desk": "TTD",
    "take-two interactive": "TTWO",
    "texas instruments": "TXN",
    "verisk analytics": "VRSK",
    "vertex pharmaceuticals": "VRTX",
    "warner bros discovery": "WBD",
    "workday": "WDAY",
    "xcel energy": "XEL",
    "zscaler": "ZS",
    "payx": "PAYX",
    "pcar": "PCAR",
    "pdd": "PDD",
    "pep": "PEP",
    "pltr": "PLTR",
    "pypl": "PYPL",
    "qcom": "QCOM",
    "regn": "REGN",
    "rop": "ROP",
    "rost": "ROST",
    "sbux": "SBUX",
    "snps": "SNPS",
    "team": "TEAM",
    "tmus": "TMUS",
    "tsla": "TSLA",
    "ttd": "TTD",
    "ttwo": "TTWO",
    "txn": "TXN",
    "vrsk": "VRSK",
    "vrtx": "VRTX",
    "wbd": "WBD",
    "wday": "WDAY",
    "xel": "XEL",
    "zs": "ZS"
}

# Subset of companies that file 20-F reports (i.e., foreign companies listed on NASDAQ)
companies_20f = {
    "arm": "ARM",
    "asml": "ASML",
    "astrazeneca": "AZN",
    "coca-cola europacific partners": "CCEP",
    "globalfoundries": "GFS",
    "pdd holdings": "PDD",
    "ccep": "CCEP",
    "gfs": "GFS",
    "pdd": "PDD",
}

# Official list of all NASDAQ-100 tickers (used for filtering or reference)
nasdaq_100_tickers = ['AAPL', 'ABNB', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AEP', 'AMAT', 'AMD', 'AMGN',
 'AMZN', 'ANSS', 'APP', 'ARM', 'ASML', 'AVGO', 'AXON', 'AZN', 'BIIB', 'BKNG',
 'BKR', 'CCEP', 'CDNS', 'CDW', 'CEG', 'CHTR', 'CMCSA', 'COST', 'CPRT', 'CRWD',
 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTSH', 'DASH', 'DDOG', 'DXCM', 'EA', 'EXC',
 'FANG', 'FAST', 'FTNT', 'GEHC', 'GFS', 'GILD', 'GOOG', 'GOOGL', 'HON', 'IDXX',
 'INTC', 'INTU', 'ISRG', 'KDP', 'KHC', 'KLAC', 'LIN', 'LRCX', 'LULU', 'MAR',
 'MCHP', 'MDB', 'MDLZ', 'MELI', 'META', 'MNST', 'MRVL', 'MSFT', 'MSTR', 'MU',
 'NFLX', 'NVDA', 'NXPI', 'ODFL', 'ON', 'ORLY', 'PANW', 'PAYX', 'PCAR', 'PDD',
 'PEP', 'PLTR', 'PYPL', 'QCOM', 'REGN', 'ROP', 'ROST', 'SBUX', 'SNPS', 'TEAM',
 'TMUS', 'TSLA', 'TTD', 'TTWO', 'TXN', 'VRSK', 'VRTX', 'WBD', 'WDAY', 'XEL', 'ZS']

# Export variables so they can be used when imported from another file
__all__ = ["company_to_ticker", "companies_20f", "nasdaq_100_tickers"]